# Generated by Django 2.0 on 2019-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0002_childy_like_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'y_user',
            },
        ),
    ]
