# Generated by Django 2.0 on 2019-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0004_childinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinfo',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
