# Generated by Django 2.0 on 2019-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0005_auto_20190508_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childy',
            name='like_num',
        ),
        migrations.AddField(
            model_name='childinfo',
            name='like_num',
            field=models.IntegerField(null=True),
        ),
    ]
