# Generated by Django 2.0 on 2019-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0009_auto_20190508_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinfo',
            name='like_num',
            field=models.IntegerField(default=100),
        ),
    ]
