# Generated by Django 2.0 on 2019-05-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0010_auto_20190508_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLikeNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user', models.CharField(max_length=15)),
                ('like_article', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'y_like',
            },
        ),
        migrations.RemoveField(
            model_name='childinfo',
            name='like_num',
        ),
        migrations.AddField(
            model_name='childy',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childlikenum',
            name='pub',
            field=models.ManyToManyField(to='y1.ChildY'),
        ),
    ]
