# Generated by Django 2.0 on 2019-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0011_auto_20190508_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='childlikenum',
            name='pub_user',
            field=models.ManyToManyField(to='y1.ChildUser'),
        ),
    ]
