# Generated by Django 2.0 on 2019-05-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0012_childlikenum_pub_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childlikenum',
            name='like_article',
        ),
        migrations.RemoveField(
            model_name='childlikenum',
            name='pub_user',
        ),
    ]
