# Generated by Django 2.0 on 2019-05-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0013_auto_20190509_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childy',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
